name: Generate and Deploy RSS News

on:
  schedule:
    - cron: '0 7 * * *'   # 毎日朝7時
    - cron: '50 11 * * *' # 毎日11:50
  workflow_dispatch: # 手動実行も可能

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages  # 必須の設定

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install feedparser jinja2

      - name: Generate HTML
        run: python generate_html.py

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './output'  # outputディレクトリを指定

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
